//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.29 at 01:01:49 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.test-soap.com/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.test_soap;
